inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false  

Metrics:
  Exclude:
    - 'db/migrate/*'

# ブロックの長さ制限
Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

# selfをつけるかどうか
Style/RedundantSelf:
  Exclude:
    - 'app/models/user.rb'
