inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false  

Metrics/AbcSize:
  Max: 32

Metrics/PerceivedComplexity:
  Max: 10

# ブロックの長さ制限
Metrics/BlockLength:
  Max: 20
  Exclude:
    - 'config/environments/development.rb'

# メソッド内のながさ制限
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'
Metrics/ClassLength:
  Max: 110

# selfをつけるかどうか
Style/RedundantSelf:
  Exclude:
    - 'app/models/user.rb'

# validation をスキップする警告を無視
Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/user.rb'
    - 'test/helpers/sessions_helper_test.rb'

# Rubyの循環的複雑度をデフォルト7から変更
CyclomaticComplexity:
  Max: 10