# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - '!docs/**'
      - '!README.md'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          rm Gemfile.lock
          bundle install --jobs 4
          bundle lock --add-platform x86_64-linux
      # Add or replace test runners here
      - name: Run tests
        run: bin/rails test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          rm Gemfile.lock
          bundle install --jobs 4
          bundle lock --add-platform x86_64-linux
      - name: run Rubocop
        run: bin/bundle exec rubocop
